# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_description', models.CharField(max_length=500)),
                ('store_image', models.FileField(default='', upload_to=b'')),
                ('store_creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
